# Ce fichier est le point d'entrée pour configurer vos propres services.
# Les fichiers dans le sous-dossier packages/ configurent vos dépendances.

# Placez ici les paramètres qui n'ont pas besoin de changer sur chaque machine où l'application est déployée
# Pour plus d'informations : https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # configuration par défaut pour les services dans *ce* fichier
    Symfony\Component\Security\Core\Security: '@security.helper'
    _defaults:
        autowire: true      # Injecte automatiquement les dépendances dans vos services.
        autoconfigure: true # Enregistre automatiquement vos services comme commandes, abonnés aux événements, etc.
    App\EventListener\PersonalCreatedListener:
        tags:
            - { name: 'kernel.event_subscriber' }    

    # Rend les classes dans src/ disponibles pour être utilisées comme services
    # cela crée un service par classe dont l'identifiant est le nom de classe complet
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}' # Exclut certains répertoires

    # Configuration spécifique pour les contrôleurs pour permettre l'injection de dépendances via les arguments de service
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
     
    # Définition manuelle de services spécifiques si nécessaire
    App\Service\ConfigService:
        # Injecte explicitement des références à d'autres services
        arguments:
            $configRepository: '@App\Repository\ConfigRepository'
            $entityManager: '@doctrine.orm.entity_manager'

    # Enregistrement des dépôts comme services si nécessaire
    App\Repository\ConfigRepository:
        # Si vous avez besoin d'arguments spécifiques ou d'appels de méthodes, définissez-les ici

    App\Security\SentimentVoter:
        tags:
            - { name: 'security.voter' }